[package]
name = "vouch"
edition = "2024.beta"
license = "MIT"
authors = ["Vouch"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }

[addresses]
vouch = "0x0"
vouch_grants = "0x0"
